"""Application-local translations for the dependency-free Settings UI.

The installed package overlays :mod:`msys_sdk`.  Keeping the small English
fallback here is deliberate: Settings must still be able to explain a broken
installation when either the SDK or its immutable catalog is unavailable.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any, Mapping

try:  # The source tree remains runnable before the SDK overlay is staged.
    from msys_sdk.i18n import CatalogError, Translator
except (ImportError, ModuleNotFoundError):  # pragma: no cover - package fallback
    CatalogError = ValueError  # type: ignore[assignment,misc]
    Translator = None  # type: ignore[assignment,misc]


ENGLISH_FALLBACK: dict[str, str] = {
    "app.title": "Settings",
    "app.name": "Settings",
    "app.summary": "Device, connectivity, audio, apps, hardware and updates",
    "nav.home": "Home",
    "nav.wifi": "Wi-Fi",
    "nav.bluetooth": "Bluetooth",
    "nav.audio": "Audio",
    "nav.display": "Display",
    "nav.appearance": "Appearance",
    "nav.apps": "Apps",
    "nav.roles": "Roles",
    "nav.hal": "Hardware",
    "nav.updates": "Updates",
    "nav.regional": "Language & region",
    "nav.system": "System",
    "nav.back": "Back",
    "nav.search": "Find a setting",
    "nav.no_results": "No matching settings",
    "home.title": "Settings",
    "home.note": "Your device, your way",
    "home.quick": "Quick settings",
    "home.more": "More settings",
    "home.wifi.note": "Networks and connectivity",
    "home.bluetooth.note": "Devices and pairing",
    "home.audio.note": "Outputs, volume and Bluetooth audio",
    "home.display.note": "Layout and orientation",
    "home.appearance.note": "Wallpaper, colors and icons",
    "home.apps.note": "Installed packages",
    "home.roles.note": "Replaceable system providers",
    "home.hal.note": "Devices and hardware providers",
    "home.updates.note": "Update and recovery",
    "home.regional.note": "Language, region and time zone",
    "home.system.note": "Runtime and isolation details",
    "home.keyboard.title": "On-screen keyboard",
    "home.keyboard.note": "Touch input and language modes",
    "regional.title": "Language & region",
    "regional.note": "Choose the interface language and device time zone",
    "regional.language": "Display language",
    "regional.language_hint": "Change the Settings interface immediately and keep the choice for the next launch.",
    "regional.language_system": "Use system language",
    "regional.language_chinese": "Chinese (Simplified)",
    "regional.language_english": "English (United States)",
    "regional.apply_language": "Apply language",
    "regional.timezone": "Time zone",
    "regional.timezone_hint": "Updates the POSIX /etc/localtime link directly when the device permits it.",
    "regional.apply_timezone": "Apply time zone",
    "regional.timezone_unavailable": "Time-zone changes are unavailable: {reason}",
    "regional.timezone_reason_zoneinfo": "the zoneinfo database is unavailable",
    "regional.timezone_reason_directory": "the localtime directory is unavailable",
    "regional.timezone_reason_invalid_path": "the localtime path is a directory",
    "regional.timezone_reason_read_only": "the localtime file is read-only",
    "regional.summary_title": "Regional preferences",
    "regional.summary": "Language: {language}\nTime zone: {timezone}",
    "regional.language_applied": "Display language updated",
    "regional.timezone_applied": "Time zone updated",
    "common.ready": "Ready",
    "common.loading": "Loading…",
    "common.refresh": "Refresh",
    "common.apply": "Apply",
    "common.cancel": "Cancel",
    "common.close": "Close",
    "common.select": "Select",
    "common.automatic": "Automatic",
    "common.unavailable": "Unavailable",
    "common.available": "Available",
    "common.connected": "Connected",
    "common.disconnected": "Disconnected",
    "common.enabled": "On",
    "common.disabled": "Off",
    "common.not_loaded": "Not loaded",
    "common.operation_failed": "Operation failed",
    "common.provider": "Provider",
    "common.device": "Device",
    "common.kind": "Kind",
    "common.security": "Security",
    "common.status": "Status",
    "common.details": "Details",
    "common.open_hal": "Manage hardware",
    "common.read": "Read",
    "common.switch": "Switch",
    "common.reset": "Reset",
    "common.reset_default": "Reset default",
    "common.use_provider": "Use provider",
    "common.use_automatic": "Use automatic",
    "common.control": "Control",
    "common.refresh_inventory": "Refresh inventory",
    "common.read_state": "Read state",
    "common.apply_changes": "Apply changes",
    "common.uninstall": "Uninstall",
    "common.check": "Check",
    "common.rollback": "Rollback",
    "common.rollback_package": "Rollback package",
    "common.package": "Package",
    "common.version": "Version",
    "status.standalone": "Standalone mode · no component event channel",
    "status.event": "System event",
    "status.loading_system": "Loading system information…",
    "status.reading_display": "Reading display settings…",
    "status.applying_layout": "Applying layout…",
    "status.loading_radio": "Loading {radio} settings…",
    "status.reading_radio": "Reading {radio} state…",
    "status.applying_radio": "Applying {radio} state…",
    "status.loading_bluetooth_devices": "Reading Bluetooth devices…",
    "status.scanning_bluetooth": "Scanning for Bluetooth devices…",
    "status.bluetooth_action": "Bluetooth: {action}…",
    "status.loading_keyboard": "Reading on-screen keyboard status…",
    "status.toggling_keyboard": "Toggling on-screen keyboard…",
    "status.loading_audio": "Reading audio state…",
    "status.selecting_audio_output": "Selecting audio output…",
    "status.setting_audio_volume": "Setting audio volume…",
    "status.setting_audio_mute": "Changing audio mute…",
    "status.saving_audio_player": "Saving squeezelite settings…",
    "status.audio_changed": "Audio changed · open Audio to refresh",
    "status.radio_changed": "{radio} changed · refresh to see the latest state",
    "status.display_migration": "Display migration #{id}: {phase}",
    "status.display_rollback": "{code}: {message}",
    "status.reading_desktop": "Reading desktop preferences…",
    "status.applying_desktop": "Applying desktop preferences…",
    "status.loading_roles": "Loading roles…",
    "status.switching_role": "Switching role provider…",
    "status.resetting_role": "Resetting role provider…",
    "status.reading_hal_inventory": "Reading hardware inventory…",
    "status.reading_ch347": "Reading CH347 output status…",
    "status.reading_hal_state": "Reading hardware state…",
    "status.applying_hal_state": "Applying hardware state…",
    "status.switching_hal_provider": "Switching hardware provider…",
    "status.resetting_hal_provider": "Restoring automatic hardware provider…",
    "status.applying_ch347_fps": "Applying CH347 frame rates…",
    "status.applying_ch347_touch": "Applying CH347 touch calibration…",
    "status.restarting_ch347": "Restarting CH347 output…",
    "status.loading_apps": "Loading installed packages…",
    "status.waiting_rollback": "Waiting for rollback health gate…",
    "status.checking_migration": "Checking display migration #{id}…",
    "status.uninstalling": "Uninstalling {package}…",
    "status.waiting_update": "Waiting for update {action}…",
    "system.title": "System",
    "system.note": "Runtime, components, services and process isolation.",
    "system.summary": "{ready}/{total} components ready · {roles} roles · {services} services",
    "system.unavailable": "MSYS service unavailable · local session details remain visible",
    "system.session": "Session",
    "system.components": "Components",
    "system.roles": "Roles",
    "system.services": "Services",
    "system.isolation": "Process isolation",
    "system.session_summary": "Settings {version} · {component} · display {display}",
    "system.components_summary": "{ready} ready · {dormant} dormant · {attention} need attention · {total} total",
    "system.roles_summary": "{active} of {total} replaceable roles have an active provider",
    "system.services_summary": "{interfaces} interfaces · {capabilities} capabilities · {total} total",
    "system.isolation_summary": "No-new-privileges {privileges} · {namespaces} namespaces · {limits} resource limits · seccomp {seccomp}",
    "system.show_diagnostics": "Show diagnostic details",
    "system.hide_diagnostics": "Hide diagnostic details",
    "display.title": "Display",
    "display.note": "Layout and outputs remain replaceable without coupling the shell to hardware.",
    "display.profile": "Profile",
    "display.orientation": "Orientation",
    "display.insets": "Safe area insets",
    "display.apply": "Apply layout",
    "display.outputs": "Outputs",
    "display.hal": "Display hardware",
    "display.summary": "Output {output} · layout {layout} · {count} display devices",
    "display.services_unavailable": "Display services unavailable · controls are disabled",
    "display.layout_ready": "ready",
    "display.layout_unavailable": "unavailable",
    "radio.wifi.title": "Wi-Fi",
    "radio.wifi.note": "Networks are supplied by a replaceable HAL provider.",
    "radio.bluetooth.title": "Bluetooth",
    "radio.bluetooth.note": "HAL controls radio power; the replaceable audio manager controls discovery and pairing.",
    "radio.provider_missing.title": "No {radio} provider",
    "radio.provider_missing.body": "Install or select a provider for the {domain} HAL domain. Settings will never show a pretend switch.",
    "radio.provider_unavailable.title": "{radio} is unavailable",
    "radio.provider_unavailable.body": "Provider {provider} reported {status}. {reason}",
    "radio.provider_ready.title": "{radio} is ready",
    "radio.provider_ready.body": "Provided by {provider}",
    "radio.no_devices": "The provider is active but reported no radio devices.",
    "radio.devices": "Devices",
    "radio.power": "Radio power",
    "radio.power_readonly": "The selected provider does not expose a writable power control.",
    "radio.select_device": "Select a device to read its live state.",
    "radio.state_unavailable": "Live state is unavailable: {message}",
    "radio.state_loaded": "Live state loaded from {provider}",
    "radio.apply_failed": "Could not change {radio}: {message}",
    "radio.network": "Wi-Fi",
    "radio.bluetooth": "Bluetooth",
    "radio.scan": "Scan",
    "radio.pair": "Pair",
    "radio.connect": "Connect",
    "radio.disconnect": "Disconnect",
    "radio.forget": "Forget",
    "radio.password": "Password (for a new network)",
    "radio.networks": "Nearby networks",
    "radio.paired": "Paired",
    "radio.not_paired": "Not paired",
    "radio.bluetooth_scan_hint": "Scan through the private BlueZ audio manager to find nearby devices.",
    "radio.bluetooth_controller_not_registered": "The Bluetooth controller is not registered with Linux Management; scanning and pairing are disabled.",
    "radio.bluetooth_audio_stack_unavailable": "The private Bluetooth audio stack is unavailable: {reason}",
    "radio.bluetooth_audio_unavailable": "Bluetooth audio management is unavailable: {reason}",
    "radio.bluetooth_scanning": "Scanning nearby Bluetooth devices…",
    "radio.bluetooth_scan_complete": "Scan complete · {count} devices",
    "radio.bluetooth_no_devices": "No devices found in 15 seconds. Put the headset in pairing mode, then scan again.",
    "radio.bluetooth_action_running": "Bluetooth {action} in progress…",
    "radio.bluetooth_action_complete": "Bluetooth {action} completed",
    "radio.bluetooth_action_failed": "Bluetooth {action} failed: {message}",
    "radio.bluetooth_forget_title": "Forget Bluetooth device?",
    "radio.bluetooth_forget_prompt": "Remove pairing information for {device}?",
    "radio.saved": "Saved",
    "radio.password_required": "Enter a password for a new Wi-Fi network.",
    "radio.forget_title": "Forget Wi-Fi network?",
    "radio.forget_prompt": "Remove the saved profile for {ssid}? You will need its credentials to connect again.",
    "radio.persistence_saved": "The network configuration was saved permanently.",
    "radio.persistence_runtime_only": "The runtime change succeeded, but wpa_supplicant could not save it permanently.",
    "radio.scan_refreshing": "Scan requested · refreshing results…",
    "radio.no_wifi_title": "No Wi-Fi device",
    "radio.no_wifi_body": "The network provider is available, but it reported no Wi-Fi interface.",
    "radio.wifi_control_degraded": "Wi-Fi control is degraded; actions are disabled.",
    "radio.wifi_control_unavailable": "Wi-Fi control is unavailable; actions are disabled.",
    "radio.hard_blocked": "Bluetooth is blocked by a hardware switch.",
    "audio.title": "Audio",
    "audio.note": "Replaceable audio output, mixer and player controls. Bluetooth pairing remains on the Bluetooth page.",
    "audio.not_loaded": "Audio state has not been loaded.",
    "audio.ready": "Audio is ready",
    "audio.unavailable": "Audio is unavailable",
    "audio.status_ready": "Backend {backend} has a connected output.",
    "audio.status_unavailable": "Backend {backend}: {reason}",
    "audio.reason_stack": "The private audio stack is not running",
    "audio.reason_controller": "The Bluetooth controller is not registered",
    "audio.reason_no_output": "No Bluetooth A2DP output is connected",
    "audio.manage_bluetooth": "Bluetooth devices",
    "audio.open_audio": "Bluetooth audio",
    "audio.stack": "Audio stack",
    "audio.stack_not_loaded": "Stack status has not been loaded.",
    "audio.stack_unavailable": "No audio stack state is available.",
    "audio.running": "Running",
    "audio.stopped": "Stopped",
    "audio.returncode": "exit {code}",
    "audio.outputs": "Playback outputs",
    "audio.output": "Output",
    "audio.no_outputs": "No connected A2DP playback outputs.",
    "audio.select_hint": "Select an output for mixer and player controls.",
    "audio.active": "Active",
    "audio.use_output": "Use selected output",
    "audio.volume": "Volume",
    "audio.volume_and_mute": "Volume and mute",
    "audio.volume_value": "{volume} · {mute}",
    "audio.volume_down": "Volume -",
    "audio.volume_up": "Volume +",
    "audio.muted": "Muted",
    "audio.unmuted": "Unmuted",
    "audio.player": "Squeezelite",
    "audio.player_not_loaded": "Player settings have not been loaded.",
    "audio.player_unavailable": "Player settings are unavailable.",
    "audio.player_status": "{enabled} · {running}",
    "audio.player_enabled": "Enable squeezelite",
    "audio.player_server": "Server (optional)",
    "audio.player_name": "Player name",
    "audio.save_player": "Save player settings",
    "keyboard.visible": "Visible · tap to hide",
    "keyboard.hidden": "Hidden · tap to show",
    "keyboard.unavailable": "No input-method provider is available",
    "appearance.title": "Appearance",
    "appearance.note": "Wallpaper, accent, icon layout and launcher preferences.",
    "appearance.show_labels": "Show icon labels",
    "appearance.invalid_response": "Launcher returned invalid preferences",
    "appearance.loaded": "Preferences loaded",
    "appearance.changed_elsewhere": "Changed elsewhere · tap Read",
    "appearance.updated": "Updated by launcher",
    "apps.title": "Apps",
    "apps.note": "Installed packages and health-gated uninstall operations.",
    "roles.title": "System roles",
    "roles.note": "Choose replaceable providers by role.",
    "roles.role_active": "Role / active provider",
    "roles.preferred": "Preferred",
    "roles.no_migration": "No display-output migration in this session",
    "roles.migration_invalid": "Display migration response was invalid",
    "roles.migration_event_invalid": "Invalid display migration event",
    "roles.migration_core_invalid": "Core returned an invalid display migration response",
    "hal.title": "Hardware",
    "hal.note": "Devices, live state and replaceable hardware providers.",
    "hal.domain": "Domain",
    "hal.provider_health_not_loaded": "Provider health not loaded",
    "hal.provider_health_unavailable": "Provider health unavailable",
    "hal.manager_unavailable": "HAL manager unavailable",
    "hal.inventory_partial": "HAL inventory unavailable · provider controls remain available",
    "hal.no_candidate": "No provider candidate",
    "hal.selected_unavailable": "Selected hardware device is unavailable",
    "hal.state_readonly": "State loaded · read-only device",
    "ch347.not_loaded": "CH347 control not loaded",
    "ch347.typed_not_loaded": "Typed interface not loaded",
    "ch347.reading_live": "Reading live driver state…",
    "ch347.waiting_status": "Waiting for CH347 status",
    "ch347.controls_ready": "CH347 controls are ready",
    "ch347.controls_disabled": "Configuration controls are disabled when the device or package state is unavailable.",
    "ch347.typed_unavailable": "Typed CH347 control unavailable",
    "ch347.saving_calibration": "Saving calibration and waiting for the output…",
    "ch347.output_ready": "CH347 output restarted and is ready",
    "ch347.window_title": "CH347 display and touch",
    "ch347.control_title": "CH347 hardware control",
    "ch347.output": "Output",
    "ch347.touch": "Touch calibration",
    "ch347.frame_rate": "Frame rate",
    "ch347.active_fps": "Active FPS",
    "ch347.idle_fps": "Idle FPS",
    "ch347.apply_frame_rates": "Apply frame rates",
    "ch347.driver": "Driver",
    "ch347.restart_note": "Restart stops and starts the supervised output. The screen may briefly go dark.",
    "ch347.restart": "Restart CH347 output",
    "ch347.calibration_note": "Calibration is stored in package state. Applying it restarts a running output.",
    "ch347.apply_touch": "Apply touch calibration",
    "ch347.touch.enabled": "Touch enabled",
    "ch347.touch.swap_xy": "Swap X / Y",
    "ch347.touch.invert_x": "Invert X",
    "ch347.touch.invert_y": "Invert Y",
    "ch347.touch.x_min": "X minimum",
    "ch347.touch.x_max": "X maximum",
    "ch347.touch.y_min": "Y minimum",
    "ch347.touch.y_max": "Y maximum",
    "ch347.touch.width": "Display width",
    "ch347.touch.height": "Display height",
    "ch347.touch.z_min": "Z minimum",
    "ch347.touch.pressure_min": "Pressure minimum",
    "ch347.touch.pressure_max": "Pressure maximum",
    "ch347.confirm_touch_title": "Apply touch calibration?",
    "ch347.confirm_touch_body": "A running CH347 output will restart so the new touch calibration takes effect. The screen may briefly go dark. Continue?",
    "ch347.touch_cancelled": "Touch calibration was not changed",
    "ch347.confirm_restart_title": "Restart CH347 output?",
    "ch347.confirm_restart_body": "The supervised display and touch output will stop and start. The screen may briefly go dark. Continue?",
    "ch347.restart_cancelled": "CH347 output was not restarted",
    "hal.state_changed_title": "State changed",
    "hal.state_changed_body": "Read the currently selected device before applying changes.",
    "hal.invalid_json": "Invalid JSON",
    "hal.invalid_changes": "Invalid changes",
    "hal.changes_object": "HAL changes must be a JSON object.",
    "apps.uninstall_title": "Uninstall package",
    "apps.select_first": "Select one installed package first.",
    "apps.select_inspect": "Select an installed package to inspect it.",
    "apps.uninstall_prompt": "Remove {package} version {version}?\n\nIts running components will be stopped and Core must pass the catalog health gate. This operation cannot be undone unless the package archive is available for reinstall.",
    "updates.rollback_title": "Rollback package",
    "updates.rollback_concrete": "Enter one concrete package id to roll back.",
    "updates.rollback_prompt": "Atomically switch {package} to its previous installed version?",
    "updates.no_request": "No update request has been sent in this session.",
    "updates.index_source": "Index URL or path",
    "updates.package_filter": "Package id or all",
    "updates.title": "Updates",
    "updates.note": "Signed updates, atomic rollback and recovery.",
}

# Keep recovery text complete for every Settings-owned UI key.  The catalog is
# normally present, but a broken package must never turn an actionable control
# into a raw translation identifier.
ENGLISH_FALLBACK.update(
    {
        "common.unknown": "Unknown",
        "status.reading_physical_rotation": "Reading physical panel rotation…",
        "status.applying_physical_rotation": "Applying physical panel rotation…",
        "status.reading_ch347_debug": "Checking CH347 display diagnostics…",
        "status.applying_ch347_debug": "Applying CH347 display debug mode…",
        "status.applying_ch347_debug_overlay": "Applying on-screen debug information...",
        "status.applying_ch347_touch_cursor": "Applying touch-cursor drawing...",
        "display.profile_mobile": "Mobile",
        "display.profile_kiosk": "Kiosk",
        "display.profile_desktop": "Desktop",
        "display.orientation_auto": "Automatic",
        "display.orientation_portrait": "Portrait",
        "display.orientation_landscape": "Landscape",
        "display.logical_layout": "Interface layout direction",
        "display.logical_layout_note": "Changes the shell layout and safe areas. It does not rotate panel pixels.",
        "display.physical_rotation": "Physical panel rotation",
        "display.physical_note": "Rotates output pixels and touch mapping only when the active display-output provider supports it.",
        "display.physical_loading": "Checking display-output capability…",
        "display.physical_ready": "Supported by the active display-output provider. Applying restarts the output briefly.",
        "display.physical_readonly": "The provider reports physical rotation as read-only.",
        "display.physical_unavailable": "Physical rotation is unavailable: {reason}",
        "display.physical_restarting": "Rotation saved; restarting the display output…",
        "display.physical_failed": "Physical rotation failed: {message}",
        "display.physical_reason_provider": "The active display-output provider does not expose this capability",
        "display.physical_reason_readonly": "The active provider exposes rotation as read-only",
        "display.physical_normal": "Normal",
        "display.physical_right": "90° clockwise",
        "display.physical_left": "90° counter-clockwise",
        "display.physical_inverted": "180°",
        "display.debug_title": "Display diagnostics",
        "display.debug_note": "Inspect the active CH347 frame limits and trusted FPS sample without treating a configured target as a measurement.",
        "display.debug_loading": "Reading display debug and FPS state…",
        "display.debug_target_fps": "Target FPS",
        "display.debug_idle_fps": "Idle FPS",
        "display.debug_capture_limit": "XCAP limit",
        "display.debug_observed_fps": "Observed FPS",
        "display.debug_generation": "Provider generation",
        "display.debug_application": "Debug state",
        "display.debug_dirty_frames": "Sent / zero-damage frames",
        "display.debug_dirty_refreshes": "Full / large refreshes",
        "display.debug_dirty_pixels": "Pixels / latest update",
        "display.debug_dirty_note": "Cumulative since the display sink started; these are not sampled rates.",
        "display.debug_enabled": "Enable FPS / dirty-region debug overlay",
        "display.debug_logging_enabled": "Detailed logging",
        "display.debug_overlay_title": "On-screen debug information",
        "display.debug_overlay_enabled": "Show debug information on screen",
        "display.debug_overlay_alpha": "Opacity (0-255)",
        "display.debug_overlay_scale": "Text scale (1x / 2x)",
        "display.debug_overlay_interval": "Refresh interval (ms)",
        "display.debug_overlay_items": "Information items",
        "display.debug_overlay_item_fps": "FPS",
        "display.debug_overlay_item_dirty": "Dirty region",
        "display.debug_overlay_item_bytes": "Transferred bytes",
        "display.debug_overlay_item_cpu": "CPU usage",
        "display.debug_overlay_item_bbox": "Bounding box",
        "display.debug_overlay_item_memory": "Memory",
        "display.debug_overlay_checking": "Checking provider support...",
        "display.debug_overlay_ready": "Supported by the active display provider.",
        "display.debug_overlay_unavailable": "The active provider does not support configurable on-screen debug information.",
        "display.debug_apply_overlay": "Apply on-screen information",
        "display.debug_overlay_unchanged": "On-screen debug information already has these values",
        "display.debug_overlay_cancelled": "On-screen debug information was not changed",
        "display.debug_overlay_confirm_title": "Apply on-screen debug information?",
        "display.debug_overlay_confirm_body": "The display provider may restart briefly while applying the overlay. Continue?",
        "display.debug_overlay_apply_failed": "Could not apply on-screen debug information: {message}",
        "display.debug_overlay_not_applied": "The provider did not confirm overlay support; no change is shown as applied.",
        "display.debug_overlay_applied": "On-screen debug information applied",
        "display.debug_cursor_title": "Touch cursor",
        "display.debug_cursor_note": "Optional touch-point drawing for diagnostics. This is independent from detailed logging and the on-screen information overlay.",
        "display.debug_cursor_enabled": "Draw the touch cursor",
        "display.debug_cursor_checking": "Checking provider support...",
        "display.debug_cursor_unavailable": "The active provider does not support configurable touch-cursor drawing.",
        "display.debug_cursor_state": "Configured {configured} · {application} · generation {generation}",
        "display.debug_cursor_state_reason": "{state} · {reason}",
        "display.debug_apply_cursor": "Apply touch cursor",
        "display.debug_cursor_unchanged": "Touch-cursor drawing already has this value",
        "display.debug_cursor_apply_failed": "Could not apply touch-cursor drawing: {message}",
        "display.debug_cursor_not_applied": "The provider did not confirm the requested touch-cursor state; no change is shown as applied.",
        "display.debug_cursor_applied": "Touch-cursor drawing applied",
        "display.debug_cursor_saved_restart": "Touch-cursor setting saved for the next provider start",
        "display.debug_cursor_result": "{message} · {state}",
        "display.debug_restart_note": "Changing this switch briefly restarts an active display provider and Settings may reopen. A stopped provider saves it for the next start.",
        "display.debug_check_fps": "Check FPS",
        "display.debug_apply_fps": "Apply rates",
        "display.debug_apply_mode": "Apply debug mode",
        "display.debug_confirm_title": "Restart display for debug mode?",
        "display.debug_confirm_body": "The active display will briefly restart and Settings may reopen. Continue applying the debug-mode change?",
        "display.debug_cancelled": "Debug mode was not changed",
        "display.debug_unchanged": "Debug mode already has this value",
        "display.debug_unavailable": "Display diagnostics unavailable: {message}",
        "display.debug_invalid_response": "The display provider returned an invalid debug response",
        "display.debug_loaded": "Display diagnostics loaded",
        "display.debug_fps_value": "{fps} FPS",
        "display.debug_not_running": "not running",
        "display.debug_runtime_applied": "applied",
        "display.debug_runtime_pending": "saved · restart required",
        "display.debug_runtime_not_applied": "not applied",
        "display.debug_application_value": "Configured {configured} · {application}",
        "display.debug_no_sample": "No trusted sample",
        "display.debug_sample": "{fps} FPS · {frames} frames / {window_ms} ms",
        "display.debug_capture_value": "Capture {fps} FPS",
        "display.debug_panel_value": "Panel {fps} FPS",
        "display.debug_frames_value": "{frames} cumulative frames",
        "display.debug_window_value": "{window_ms} ms sample window",
        "display.debug_dirty_frames_value": "{sent_frames} sent · {zero_damage} zero-damage",
        "display.debug_dirty_refreshes_value": "{full_refreshes} full · {large_refreshes} large",
        "display.debug_dirty_pixels_value": "{sent_pixels} total · {last_sent_pixels} last · {last_rects} rects",
        "display.debug_status_active": "active",
        "display.debug_status_idle": "idle",
        "display.debug_status_unavailable": "sample unavailable",
        "display.debug_reason_none": "no additional detail",
        "display.debug_reason_disabled": "debug overlay is disabled",
        "display.debug_reason_pending": "configuration is not active yet",
        "display.debug_reason_awaiting": "waiting for the first real debug sample",
        "display.debug_reason_measured": "measured from the sink debug log",
        "display.debug_check_result": "FPS check {status} · {reason}",
        "display.debug_apply_failed": "Could not apply display diagnostics: {message}",
        "display.debug_saved_restart": "Debug mode saved; it will apply when the display provider starts",
        "display.debug_applied": "Debug mode applied to the active display provider",
        "radio.bluetooth_nearby": "Nearby Bluetooth devices",
        "radio.bluetooth_scan_hint": "Scan through the private BlueZ audio manager to find nearby devices.",
        "radio.bluetooth_discovery_unavailable": "This controller has no usable Linux Management discovery channel.",
        "radio.bluetooth_power_to_scan": "Turn Bluetooth on before scanning.",
        "radio.bluetooth_found": "Found {count} nearby devices",
        "radio.address": "Address",
        "radio.signal": "Signal",
        "radio.security_open": "Open",
        "radio.security_secured": "Secured",
        "radio.security_saved": "Saved",
        "radio.password_invalid": "Use an 8–63 character ASCII passphrase or a 64-digit hexadecimal key.",
        "appearance.layout": "Layout",
        "appearance.wallpaper": "Wallpaper",
        "appearance.accent": "Accent",
        "appearance.icon_size": "Icon size",
        "appearance.sort": "Sort",
        "appearance.layout_profile": "Profile default",
        "appearance.layout_auto": "Automatic",
        "appearance.layout_mobile": "Mobile",
        "appearance.layout_desktop": "Desktop",
        "appearance.layout_kiosk": "Kiosk",
        "appearance.sort_name": "Name",
        "appearance.sort_component": "Component",
        "appearance.preview_settings": "Settings",
        "appearance.preview_files": "Files",
        "appearance.preview_app": "App",
        "appearance.revision": "Revision {revision}",
        "roles.default_provider": "Profile default",
        "roles.select_role": "Select a role",
        "roles.migration_rollback_fallback": "Display migration rolled back",
        "roles.migration_bad_response": "Core did not return a valid planned migration",
        "roles.migration_request_failed": "Display migration request failed · {code}",
        "roles.migration_pending_request": "Pending display-output request → {provider}",
        "roles.migration_pending": "Pending display migration #{id} · {phase} · {source} → {target}",
        "roles.migration_succeeded": "Display migration #{id} succeeded · active {provider}",
        "roles.migration_rolled_back": "Display migration #{id} rolled back · {code}: {message}",
        "roles.migration_status_unavailable": "Pending display migration #{id} · status unavailable",
        "roles.migration_not_selected": "The requested provider was not selected.",
        "roles.migration_active_unchanged": "The active provider remains unchanged until succeeded.",
        "hal.select_device_hint": "Select a device and tap Read to inspect its state.",
        "hal.reload_failed": "{notice}; reload failed",
        "hal.hardware_unavailable": "Hardware information unavailable",
        "hal.manager_not_running": "HAL manager is not installed or not running",
        "hal.other_pages_available": "Other Settings pages remain available.",
        "hal.summary": "{domains} domains · {devices} devices",
        "hal.summary_unavailable": "{count} unavailable",
        "hal.summary_inventory_unavailable": "inventory unavailable",
        "hal.summary_provider_controls_unavailable": "provider controls unavailable",
        "hal.provider_management_unavailable": "HAL provider management is unavailable",
        "hal.read_editable_hint": "Tap Read to load editable values.",
        "hal.device_unavailable_hint": "This device is currently unavailable.",
        "hal.no_domains": "No HAL domains were reported.",
        "hal.provider_latency": "{latency} ms",
        "hal.legacy_health_not_reported": "legacy HAL: capabilities/health not reported",
        "hal.selection_disabled": "selection disabled",
        "hal.editable": "Editable: {fields}",
        "hal.provider_conflict_reloaded": "Provider catalog changed; reloaded before applying",
        "hal.domain_changed": "{domain} changed · tap Refresh",
        "ch347.controls": "CH347 controls",
        "ch347.control_unavailable": "CH347 control unavailable: {message}",
        "ch347.summary": "CH347 {status} · {running} · {fps}/{idle_fps} FPS",
        "ch347.running": "Running",
        "ch347.stopped": "Stopped",
        "ch347.status": "{status} · {running}",
        "ch347.reason_unknown": "unknown reason",
        "ch347.detail_component": "component: {component}",
        "ch347.detail_processes": "processes: {count}",
        "ch347.detail_package": "package {version}",
        "ch347.detail_configuration": "configuration: {errors}",
        "ch347.configuration_not_provisioned": "installed driver state is not provisioned",
        "ch347.provider_not_responding": "The provider is not installed or not responding.",
        "ch347.no_state": "CH347 control returned no state",
        "ch347.whole_number_required": "{field}: whole number required",
        "ch347.frame_rate_update_failed": "Frame-rate update failed",
        "ch347.frame_rates_applied": "Frame rates applied: {fps} FPS, idle {idle_fps} FPS",
        "ch347.calibration_update_failed": "Calibration update failed",
        "ch347.touch_applied_running": "Touch calibration applied; the running output restarted successfully",
        "ch347.touch_saved": "Touch calibration saved for the next output start",
        "ch347.restart_failed": "Restart failed",
        "apps.unavailable": "Installed packages unavailable",
        "apps.summary": "{count} installed package(s)",
        "apps.uninstalled_refreshing": "Uninstalled {package}; refreshing…",
        "apps.uninstall_failed": "Uninstall failed: {reason}",
    }
)

ENGLISH_FALLBACK.update(
    {
        "software_center.title": "Software Center",
        "software_center.name": "Software Center",
        "software_center.summary": "Installed software, updates and recovery",
        "nav.storage": "Storage",
        "home.storage.note": "TF cards, USB drives and automatic mounting",
        "home.calibration.title": "Touch calibration",
        "home.calibration.checking": "Checking whether calibration is installed",
        "home.calibration.ready": "Calibrate touch points and save the mapping",
        "home.calibration.unavailable": "Calibration app is not installed",
        "home.calibration.started": "Touch calibration opened",
        "status.checking_calibration": "Checking touch calibration…",
        "status.starting_calibration": "Opening touch calibration…",
        "status.loading_storage": "Reading removable storage…",
        "status.saving_storage": "Saving automatic mounting…",
        "status.mounting_storage": "Mounting volume…",
        "status.unmounting_storage": "Unmounting volume…",
        "apps.installed": "Installed",
        "apps.package_not_found": "Package {package} is not installed.",
        "storage.title": "Storage",
        "storage.note": "Manage TF cards, USB drives and the lightweight automatic mount policy.",
        "storage.not_loaded": "Storage not loaded",
        "storage.waiting": "Waiting for the storage provider",
        "storage.unavailable": "Storage provider unavailable",
        "storage.ready": "Removable storage",
        "storage.summary": "{count} volume(s) · managed below {root}",
        "storage.no_volumes": "No removable TF card or USB volume was found.",
        "storage.auto_mount": "Mount removable media automatically",
        "storage.mounted": "Mounted",
        "storage.not_mounted": "Not mounted",
        "storage.mount": "Mount",
        "storage.unmount": "Unmount",
        "storage.volume_error": "Last operation failed: {reason}",
        "appearance.desktop_options": "Desktop layout and effects",
        "appearance.wallpaper_path": "Wallpaper PPM path",
        "appearance.wallpaper_path_hint": "Use an absolute, pre-scaled PPM image. Acrylic uses a static pre-blurred surface; no real-time blur is rendered.",
        "appearance.grid_columns": "Grid columns (0 = auto)",
        "appearance.grid_rows": "Grid rows (0 = auto)",
        "appearance.acrylic": "Use lightweight acrylic surfaces",
        "appearance.navigation_mode": "Navigation style",
        "appearance.layout_embedded": "Embedded panel",
        "appearance.navigation_buttons": "Back / Home / Recent buttons",
        "appearance.navigation_pill": "Gesture pill",
        "appearance.icon_spacing": "Icon spacing",
        "appearance.folders_enabled": "Enable desktop folders",
        "appearance.large_folders_enabled": "Allow large desktop folders",
        "appearance.animations_enabled": "Enable lightweight animations",
        "appearance.reduce_motion": "Reduce motion",
        "appearance.live_apply_note": "These launcher preferences apply live. X11 and the SPI output are not restarted.",
    }
)


class SettingsI18n:
    """Safe facade over the shared catalog implementation."""

    def __init__(
        self,
        catalog_path: str | os.PathLike[str] | None = None,
        *,
        locale: str | None = None,
        environ: Mapping[str, str] | None = None,
    ) -> None:
        self.catalog_path = Path(catalog_path) if catalog_path else default_catalog_path()
        self.load_error = ""
        self._translator: Any = None
        if Translator is not None:
            try:
                self._translator = Translator.from_file(
                    self.catalog_path,
                    locale,
                    environ=environ,
                )
            except (CatalogError, OSError, UnicodeError, ValueError) as exc:
                self.load_error = str(exc)

    @property
    def locale(self) -> str:
        if self._translator is None:
            return "en-US"
        return str(self._translator.resolved_locale)

    def text(
        self,
        key: str,
        params: Mapping[str, object] | None = None,
        *,
        fallback: str | None = None,
    ) -> str:
        english = fallback if fallback is not None else ENGLISH_FALLBACK.get(key, key)
        if self._translator is None:
            return _render_fallback(english, params)
        return str(self._translator.text(key, params, fallback=english))

    __call__ = text


def default_catalog_path() -> Path:
    configured = os.environ.get("MSYS_I18N_CATALOG")
    if configured:
        return Path(configured)
    return Path(__file__).resolve().parents[2] / "share" / "i18n" / "catalog.json"


def _render_fallback(
    template: str,
    params: Mapping[str, object] | None,
) -> str:
    rendered = template
    for key, value in (params or {}).items():
        if isinstance(value, str) or (
            isinstance(value, int) and not isinstance(value, bool)
        ):
            rendered = rendered.replace("{" + str(key) + "}", str(value))
    return rendered


__all__ = ["ENGLISH_FALLBACK", "SettingsI18n", "default_catalog_path"]
